package Entity;

import java.util.*;

/**
 * Created by Alexander on 15.12.2015.
 */
public class Shop{
    public static int getSize() {
        return size;
    }

    private static int size = 0;

    public synchronized void generateAnimal(){
        Random r = new Random();

        Animal result = new Animal(Integer.toString(r.nextInt(100)),"autogenerated_name"+Integer.toString(r.nextInt(100)),"",Integer.toString(r.nextInt(10000)),"dog");
        this.getContent().add(result);
        result.start();
        result.generate();
        this.generateBuyer();
    }


    public Shop(int size, List<Animal> content) {
        this.size = size;
        this.content = content;

        Timer timer = new Timer();
        TimerTask tt = new TimerTask() {
            @Override
            public void run() {
                generateAnimal();
            }
        };
        timer.schedule(tt, 1);

        TimerTask tt1 = new TimerTask() {
            @Override
            public void run() {
                generateBuyer();
            }
        };
        timer.schedule(tt1,2);
    }

    public synchronized void generateBuyer(){
        Random r = new Random();
        List<Animal> emptyList = new ArrayList<Animal>();
        Buyer result = new Buyer("Autogenerated"+Integer.toString(r.nextInt(100)), emptyList);
        result.start();
    }
    private List<Animal> content;

    public List<Animal> getContent(){
        return content;
    }

}
